### ISSUE TITLE
[Request] Add a commands blacklist

### ISSUE THREAD

**Issue by CamperSamu** [Thomilist/dimensional-inventories#2]
This is not really needed since LuckPerms allows you to allow/disallow actions based on the dimension, but this might come in handy for less techincal setups.
If you don't want to do this, I'd suggest to mention in the readme that LuckPerms allows for blacklisting of specific permission nodes by world/dimension and should be coupled with [Vanilla Permissions](https://modrinth.com/mod/vanilla-permissions) and/or [Universal Perms](https://modrinth.com/mod/universal-perms)

**Comment by Thomilist** [comment]
I think such management of commands isn't much different from actual permission management, which I consider outside the scope of this mod. It is better handled by dedicated permission mods such as LuckPerms, as you mention. 

However, I'll gladly add this information to the readme. I have now added a tips section mentioning per-dimension permissions as well as giving a usage example with teleport commands. This example is roughly what I use myself, so it makes sense to show it here as well. Hopefully, it will at least guide people in the right direction. 

Thank you for your input :)

**Comment by CamperSamu** [comment]
Glad to contribute!
