### ISSUE TITLE
Parrots are not changed between dimensions 

### ISSUE THREAD

**Issue by Daniel99j2** [Thomilist/dimensional-inventories#9]
When changing dimension pools, parrots sitting in your shoulder do not get removed. A config option may be useful to enable it.

**Comment by Thomilist** [comment]
Fixed in the latest release ([2.1.0+1.21.1](https://github.com/Thomilist/dimensional-inventories/releases/tag/2.1.0%2B1.21.1)). Thank you for pointing it out :)
